id: I0279F467
legacy_id: P004532
ocr_import_info:
  bdrc_scan_id: W1CZ2515
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T13:59:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:22:33.842845+00:00'
last_modified: 2022-08-31 03:23:00.187351
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2515
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2515
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་མཐའ་ཀུན་ཤེས་རྩ་འགྲེལ།
  author: སྟག་ཚང་ལོ་ཙཱ་བ་ཤེས་རབ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.7513586803683532
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1CZ2534:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2534
      total_pages: 325
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2534.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7513586803683532
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
