id: P004532
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ2515
  title: གྲུབ་མཐའ་ཀུན་ཤེས་རྩ་འགྲེལ
  author: ''
  volumes:
    3af3da7e7571457b870c1aca442046cc:
      image_group_id: I1CZ2534
      title: ''
      volume_number: 1
      total_pages: 325
      base_file: v001.txt
